---
layout: post
title: new Fed's Chair
tags: finance
---

Sooner or later, Trump will replace a new Fed's chair. This post collects some interesting articles relating to this change. Some links are about monetary policies in theory and practices, that I almost have no understanding before. :laughing:

It will be updated when I read new interesting things about this topic.

### 1. Some links about the new Fed's Chair
- J. Powell vs. John B. Taylor: read [here](https://mobile.nytimes.com/2017/10/24/us/politics/trump-fed-powell-taylor-yellen.html?_r=0&referer=)

- Taylor seems to publicly criticize Fed's policies:
    - In an interview from WSJ, he suggested "to normalize" the monetary policies as in 80-90s period: [here](http://www.wsj.com/video/opinion-journal-why-the-fed-failed/2B2ACF6F-3766-432A-9C64-D8448573D487.html) 
    
- Powell has 5-year experience at Fed, tends to continue the cautious policy. Some of his words:

>“Let’s let the data speak: The evidence so far is clear that the benefits of these policies have been substantial and that the risks have not materialized” (Powell, 2005)

>“Simple policy rules are widely thought to be both interesting and useful, but to represent only a small part of the analysis needed to assess the appropriate path for policy. I am unable to think of any critical, complex human activity that could be safely reduced to a simple summary equation. In particular, no major central bank uses policy rules in a prescriptive way, and it is hard to predict the consequences of requiring the [Federal Open Market Committee] to do so, as some have proposed. policy should be systematic, but not automatic.” (Powell, 2017 February)

:laughing: this simple summary equation is Taylor rule?


### 2. Some links about monetary polices
- A recent monetary policy report by [Yellen](https://www.federalreserve.gov/monetarypolicy/files/20170707_mprfullreport.pdf).

- Taylor rule: written by [Woodford](https://www.uni-erfurt.de/fileadmin/user-docs/Makrooekonomie/SS2013/MA_MakroII/Woodford_2001_-_The_Taylor_Rule_and_Optimal_Monetary_Policy.pdf). A fact is that no one watches economists talk in Youtube. I used to read comments in a Ted talk by R. Shiller, and most of comments are so bad! Woodford has a talk, and I see only seen around >1k times :joy:

